### ISSUE TITLE
Security Verification Error

### ISSUE THREAD

**Issue by Jenks632** [cardstream/WooCommerce#2]
Good Morning

A client of my organization is experiencing issues with their ECOM; they are using the WooCommerce Cardstream Plugin (latest version) and some customers are experiencing a failure to load the payment portal, it just shows a loading pinwheel and nothing happens. On the Cardstream side it shows that the 3D Secure form is waiting to be completed (i.e. the payment gateway is waiting to be completed).

The website is setup for Hosted Integration and is only effecting a few customers. Latest versions of Woo and WP are being used. My colleague did manage get an error page to generate which I have attached in a screenshot. It's also worth noting this is the only client experiencing this issue to our knowledge.

![screen](https://user-images.githubusercontent.com/72248497/94900108-56047f80-048c-11eb-99db-bbf6cae7fc8a.png)

Any assistance you can provide would be grateful.

**Comment by cardstreamltd** [comment]
Good morning,

Thank you for reaching out to us with this issue.

From the attached screenshot we can see that the issue looks to be related to the ACS which is outside of our control and not actually related to this module. We would also like to note that this issue should really be raised direct to Yorkshire Payments rather than to us.

Please could you raise the query with them so that it can be logged into our ticketing system for tracking.

As a result of our comments above, we will now close this issue.

Kind regards,
Cardstream
